services:
  postgresql:
    container_name: amt-ai-postgres
    image: postgres:15.7
    ports:
      - '${DB_PORT:-5432}:5432'
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-uk-learning}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '${API_PORT:-8000}:8000'
    command: >
      sh -c "alembic upgrade head && uvicorn server:app --host 0.0.0.0 --port 8000 --workers 1"
    depends_on:
      - postgresql


volumes:
  postgres-data:

networks:
  uk-learning-network:
    driver: bridge